# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_F1M1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F1M2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F1M3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F1M4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F2M1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F2M2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F2M3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F2M4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F3M1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F3M2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F3M3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_F3M4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint_1:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint_2:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint_3:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint_4:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint_5:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint_6:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint_7:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  right_F1M1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F1M2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F1M3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F1M4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F2M1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F2M2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F2M3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F2M4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F3M1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F3M2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F3M3:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_F3M4:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint_1:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint_2:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint_3:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint_4:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint_5:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint_6:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint_7:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0