left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_joint_1
    - left_joint_2
    - left_joint_3
    - left_joint_4
    - left_joint_5
    - left_joint_6
    - left_joint_7
  gains:
    left_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_joint_1
    - right_joint_2
    - right_joint_3
    - right_joint_4
    - right_joint_5
    - right_joint_6
    - right_joint_7
  gains:
    right_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_F1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_F1M1
    - right_F1M2
    - right_F1M3
    - right_F1M4
  gains:
    right_F1M1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_F1M2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_F1M3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_F1M4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_F2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_F2M1
    - right_F2M2
    - right_F2M3
    - right_F2M4
  gains:
    right_F2M1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_F2M2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_F2M3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_F2M4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_F3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_F3M1
    - right_F3M2
    - right_F3M3
    - right_F3M4
  gains:
    right_F3M1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_F3M2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_F3M3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_F3M4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_F1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_F1M1
    - left_F1M2
    - left_F1M3
    - left_F1M4
  gains:
    left_F1M1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_F1M2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_F1M3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_F1M4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_F2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_F2M1
    - left_F2M2
    - left_F2M3
    - left_F2M4
  gains:
    left_F2M1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_F2M2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_F2M3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_F2M4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_F3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_F3M1
    - left_F3M2
    - left_F3M3
    - left_F3M4
  gains:
    left_F3M1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_F3M2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_F3M3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_F3M4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1